-- Article extractive summary, generated by facebook/bart-large-cnn (HF task: Summarization).
-- Stored separately from the verdict's narrative report so we can translate
-- and surface both side-by-side in the demo.
ALTER TABLE verification_runs ADD COLUMN IF NOT EXISTS article_summary TEXT;
